// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
export {}
        
declare module 'vue' {
  export interface GlobalComponents {
    ActiveVehicleItem: typeof import('./src/app/vehicles/ActiveVehicleItem.vue')['default']
    ActiveVehicles: typeof import('./src/app/vehicles/ActiveVehicles.vue')['default']
    AddVehicles: typeof import('./src/app/vehicles/AddVehicles.vue')['default']
    AddVehiclesBulkVIN: typeof import('./src/app/vehicles/AddVehiclesBulkVIN.vue')['default']
    AddVehiclesManualEntry: typeof import('./src/app/vehicles/AddVehiclesManualEntry.vue')['default']
    AddVehiclesSingleVIN: typeof import('./src/app/vehicles/AddVehiclesSingleVIN.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VApp: typeof import('vuetify/lib')['VApp']
    VAppBar: typeof import('vuetify/lib')['VAppBar']
    VAvatar: typeof import('vuetify/lib')['VAvatar']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VCard: typeof import('vuetify/lib')['VCard']
    VCardActions: typeof import('vuetify/lib')['VCardActions']
    VCardText: typeof import('vuetify/lib')['VCardText']
    VCardTitle: typeof import('vuetify/lib')['VCardTitle']
    VCol: typeof import('vuetify/lib')['VCol']
    VContainer: typeof import('vuetify/lib')['VContainer']
    VDialog: typeof import('vuetify/lib')['VDialog']
    VDivider: typeof import('vuetify/lib')['VDivider']
    VExpandTransition: typeof import('vuetify/lib')['VExpandTransition']
    VFooter: typeof import('vuetify/lib')['VFooter']
    VForm: typeof import('vuetify/lib')['VForm']
    VIcon: typeof import('vuetify/lib')['VIcon']
    VMain: typeof import('vuetify/lib')['VMain']
    VResponsive: typeof import('vuetify/lib')['VResponsive']
    VRow: typeof import('vuetify/lib')['VRow']
    VSnackbar: typeof import('vuetify/lib')['VSnackbar']
    VSpace: typeof import('vuetify/lib')['VSpace']
    VSpacer: typeof import('vuetify/lib')['VSpacer']
    VTab: typeof import('vuetify/lib')['VTab']
    VTabItem: typeof import('vuetify/lib')['VTabItem']
    VTabs: typeof import('vuetify/lib')['VTabs']
    VTabsItems: typeof import('vuetify/lib')['VTabsItems']
    VTextField: typeof import('vuetify/lib')['VTextField']
    VToolbar: typeof import('vuetify/lib')['VToolbar']
    VToolbarTitle: typeof import('vuetify/lib')['VToolbarTitle']
  }
}
